# Generated by Django 3.0.6 on 2020-05-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Повод')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала события')),
                ('date_end', models.DateField(verbose_name='Дата конца события')),
                ('event_name', models.CharField(max_length=60, verbose_name='Название события')),
                ('players', models.CharField(max_length=90, verbose_name='Участники')),
                ('reason', models.CharField(max_length=60, verbose_name='Повод')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Qualific_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала квалификации')),
                ('date_end', models.DateField(verbose_name='Дата конца квалификации')),
                ('place', models.CharField(max_length=100, verbose_name='Место квалификации')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('document', models.FileField(upload_to='documents_qualific/', verbose_name='Потдверждающий документ')),
                ('time', models.IntegerField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Курс повышения квалификации',
                'verbose_name_plural': 'Курсы повышения квалификации',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual_name', models.CharField(max_length=50, verbose_name='Название квалификации')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=45, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=45, verbose_name='Имя')),
                ('father_name', models.CharField(max_length=45, verbose_name='Отчество')),
                ('image', models.ImageField(null=True, upload_to='photos/', verbose_name='Фотография')),
                ('last_attest', models.DateField(verbose_name='Последняя аттестация')),
                ('next_attest', models.DateField(verbose_name='Следующая аттестация')),
                ('educ_place', models.CharField(max_length=120, verbose_name='Место обучения')),
                ('rang', models.CharField(max_length=45, verbose_name='Ранг')),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Qualification', verbose_name='Квалификация')),
                ('roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Type_educ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educ_name', models.CharField(max_length=50, verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='Teachers_has_type_educ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id_educ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Teacher', verbose_name='Преподаватель')),
                ('type_educ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Type_educ', verbose_name='Тип образования')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_has_qualific_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualific_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Qualific_course', verbose_name='Курс повышения квалификации')),
                ('teacher_id_qualific', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_has_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Event', verbose_name='Событие')),
                ('teacher_id_eve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Staging_on_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('teacher_name', models.CharField(max_length=90, verbose_name='ФИО преподавателя')),
                ('teacher_role', models.CharField(max_length=60, verbose_name='Роль преподавателя')),
                ('teacher_id_stag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Постановка',
                'verbose_name_plural': 'Постановки',
            },
        ),
        migrations.CreateModel(
            name='Criterie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(verbose_name='Балл')),
                ('categoryes_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
        migrations.CreateModel(
            name='Achievements_has_teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Achievement', verbose_name='Достижение')),
                ('teacher_id_achiev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='criterie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Criterie', verbose_name='Критерий'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='event_in_achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Event', verbose_name='Событие'),
        ),
    ]
