# Generated by Django 3.0.6 on 2020-05-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='url',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
