# Generated by Django 3.0.7 on 2020-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20200617_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='rang',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=60, null=True, verbose_name='Квалификация/разряд/соответсвие ПС'),
        ),
    ]
