# Generated by Django 3.0.7 on 2020-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20200617_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pck',
            field=models.CharField(choices=[('Преподаватель', 'Преподаватель'), ('Методист', 'Методист'), ('Председатель ПЦК', 'Председатель ПЦК')], max_length=100, null=True, verbose_name='ПЦК, к которому относится сотрудник'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Преподаватель', 'Преподаватель'), ('Методист', 'Методист'), ('Председатель ПЦК', 'Председатель ПЦК')], max_length=100, null=True, verbose_name='Роль сотрудника в системе'),
        ),
    ]
