# Generated by Django 3.0.7 on 2020-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20200617_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pck',
            field=models.CharField(choices=[('ПЦК электро-технических дисциплин', 'ПЦК электро-технических дисциплин'), ('ПЦК химико-экологических дисциплин', 'ПЦК химико-экологических дисциплин'), ('ПЦК информационных дисциплин', 'ПЦК информационных дисциплин'), ('ПЦК теплотехнических дисциплин', 'ПЦК теплотехнических дисциплин'), ('ПЦК информационных дисциплин', 'ПЦК информационных дисциплин')], max_length=100, null=True, verbose_name='ПЦК, к которому относится сотрудник'),
        ),
    ]
