# Generated by Django 3.0.7 on 2020-06-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20200617_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements_has_teachers',
            name='achievements_id',
        ),
        migrations.RemoveField(
            model_name='achievements_has_teachers',
            name='teacher_id_achiev',
        ),
        migrations.RemoveField(
            model_name='staging_on_teacher',
            name='teacher_id_stag',
        ),
        migrations.AddField(
            model_name='evaluation_system',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата конца события'),
        ),
        migrations.AddField(
            model_name='evaluation_system',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата начала события'),
        ),
        migrations.AddField(
            model_name='evaluation_system',
            name='document_for_event',
            field=models.FileField(null=True, upload_to='document_for_event/', verbose_name='Потдверждающий документ'),
        ),
        migrations.AddField(
            model_name='evaluation_system',
            name='event_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Название события'),
        ),
        migrations.AddField(
            model_name='evaluation_system',
            name='teacher_role',
            field=models.CharField(choices=[('Организатор', 'Организатор'), ('Участник', 'Участник')], max_length=60, null=True, verbose_name='Роль преподавателя в мероприятии'),
        ),
        migrations.AlterField(
            model_name='evaluation_system',
            name='subcategory_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Название критерия мероприятия'),
        ),
        migrations.AlterField(
            model_name='qualification_course',
            name='document',
            field=models.FileField(upload_to='documents_for_qualific/', verbose_name='Потдверждающий документ'),
        ),
        migrations.AlterField(
            model_name='teachers_has_event',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Evaluation_system', verbose_name='Событие'),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Achievements_has_teachers',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Staging_on_teacher',
        ),
    ]
