# Generated by Django 3.0.7 on 2020-06-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_teacher_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pck_name', models.CharField(choices=[('ПЦК электро-технических дисциплин', 'ПЦК электро-технических дисциплин'), ('ПЦК химико-экологических дисциплин', 'ПЦК химико-экологических дисциплин'), ('ПЦК информационных дисциплин', 'ПЦК информационных дисциплин'), ('ПЦК теплотехнических дисциплин', 'ПЦК теплотехнических дисциплин'), ('ПЦК информационных дисциплин', 'ПЦК информационных дисциплин')], max_length=100, null=True, verbose_name='ПЦК, к которому относится сотрудник')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='pck',
        ),
        migrations.CreateModel(
            name='Teachers_in_PCK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Evaluation_system', verbose_name='Событие')),
                ('teacher_id_pck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='pck_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.PCK', verbose_name='ПЦК, в котором состоит преподаватель'),
        ),
    ]
