# Generated by Django 3.0.7 on 2020-06-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_auto_20200618_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pck',
            options={'verbose_name': 'Курс повышения квалификации', 'verbose_name_plural': 'Курсы повышения квалификации'},
        ),
    ]
