# Generated by Django 3.0.7 on 2020-06-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_auto_20200618_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pck',
            options={'verbose_name': 'Предметно-цикловая комиссия', 'verbose_name_plural': 'Предметно-цикловые комиссии'},
        ),
    ]
