# Generated by Django 3.0.7 on 2020-06-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_auto_20200618_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pck',
            name='pck_name',
            field=models.CharField(max_length=100, null=True, verbose_name='ПЦК, к которому относится сотрудник'),
        ),
        migrations.AlterField(
            model_name='teachers_in_pck',
            name='pck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Evaluation_system', verbose_name='ПЦК, к которому относится сотрудник'),
        ),
    ]
