# Generated by Django 3.0.7 on 2020-06-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_auto_20200618_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_in_pck',
            name='pck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.PCK', verbose_name='ПЦК, к которому относится сотрудник'),
        ),
    ]
