# Generated by Django 3.0.7 on 2020-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_auto_20200618_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers_has_event',
            options={'verbose_name': '!СВЯЗУЮЩАЯ!Преподаватель + события', 'verbose_name_plural': '!СВЯЗУЮЩАЯ!Преподаватели + события'},
        ),
        migrations.AlterModelOptions(
            name='teachers_has_qualific_course',
            options={'verbose_name': '!СВЯЗУЮЩАЯ!Преподаватели + квалификационный курс', 'verbose_name_plural': '!СВЯЗУЮЩАЯ!Преподаватели + квалификационные курсы'},
        ),
        migrations.AlterModelOptions(
            name='teachers_in_pck',
            options={'verbose_name': '!СВЯЗУЮЩАЯ!Преподаватели + ПЦК', 'verbose_name_plural': '!СВЯЗУЮЩАЯ!Преподаватели + ПЦК'},
        ),
    ]
