# Generated by Django 3.0.7 on 2020-06-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_auto_20200618_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers_has_event',
            options={'verbose_name': '__!СВЯЗУЮЩАЯ!__Преподаватель + события', 'verbose_name_plural': '__!СВЯЗУЮЩАЯ!__Преподаватели + события'},
        ),
        migrations.AlterModelOptions(
            name='teachers_has_qualific_course',
            options={'verbose_name': '__!СВЯЗУЮЩАЯ!__Преподаватели + квалификационный курс', 'verbose_name_plural': '__!СВЯЗУЮЩАЯ!__Преподаватели + квалификационные курсы'},
        ),
        migrations.AlterModelOptions(
            name='teachers_in_pck',
            options={'verbose_name': '__!СВЯЗУЮЩАЯ!__Преподаватели + ПЦК', 'verbose_name_plural': '__!СВЯЗУЮЩАЯ!__Преподаватели + ПЦК'},
        ),
    ]
