# Generated by Django 3.0.7 on 2020-06-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_auto_20200618_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='url',
        ),
    ]
