# Generated by Django 3.0.7 on 2020-06-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_remove_teacher_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='image',
            new_name='photo',
        ),
    ]
