# Generated by Django 3.0.7 on 2020-06-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers_has_qualific_course',
            options={'verbose_name': '__!СВЯЗУЮЩАЯ!__Преподаватель + события', 'verbose_name_plural': '__!СВЯЗУЮЩАЯ!__Преподаватели + события'},
        ),
        migrations.RemoveField(
            model_name='teachers_has_event',
            name='teacher_id_eve',
        ),
        migrations.AddField(
            model_name='teachers_has_event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers_has_event',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Teacher'),
        ),
        migrations.AlterField(
            model_name='teachers_has_event',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Evaluation_system'),
        ),
    ]
