# Generated by Django 3.0.7 on 2020-06-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_auto_20200619_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers_has_event',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
