# Generated by Django 3.0.7 on 2020-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_auto_20200619_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ball',
        ),
        migrations.AddField(
            model_name='tag',
            name='ball',
            field=models.IntegerField(null=True, verbose_name='Балл'),
        ),
    ]
