# Generated by Django 3.0.7 on 2020-06-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_auto_20200619_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'событие', 'verbose_name_plural': 'события'},
        ),
    ]
