# Generated by Django 3.0.7 on 2020-06-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0033_auto_20200619_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
