# Generated by Django 3.0.7 on 2020-06-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0035_auto_20200619_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date_created',
        ),
    ]
