# Generated by Django 3.0.7 on 2020-06-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0036_remove_activity_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_in_pck',
            name='pck_id',
        ),
        migrations.RemoveField(
            model_name='teachers_in_pck',
            name='teacher_id_pck',
        ),
        migrations.DeleteModel(
            name='Teachers_has_qualific_course',
        ),
        migrations.DeleteModel(
            name='Teachers_in_PCK',
        ),
    ]
