# Generated by Django 3.0.7 on 2020-06-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0037_auto_20200619_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='note',
        ),
    ]
