# Generated by Django 3.0.7 on 2020-06-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0038_remove_activity_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название события'),
        ),
    ]
