# Generated by Django 3.0.7 on 2020-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0045_auto_20200621_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='note',
            field=models.CharField(max_length=200, null=True, verbose_name='Заметка к событию'),
        ),
    ]
